FROM ubuntu

MAINTAINER hnam <hnam@student.42.us.org>

RUN apt-get update && apt-get upgrade -y && apt-get install -y nodejs npm git vim emacs

RUN npm install yarn --global && npm install npm --global
